Repository Alfresco/alfresco-java-sdk, pull requests merged in 2022-05, with the labels that each got.

#149 ISSUE-119 Change parent for samples module
  samples/pom.xml
Labels: PR: reviewed-approved

#147 MNT-22946: bump springboot version to 2.5.12
  pom.xml
Labels: PR: reviewed-approved

#150 MNT-22946: bump springboot version to 2.5.12
  samples/pom.xml
Labels: PR: reviewed-approved

#146 REPO-5699 Include ACS Model API to alfresco-java-sdk
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/patch.sh
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-spring-boot/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-spring-boot/src/main/java/org/alfresco/rest/sdk/config/AlfrescoRestApiAutoConfiguration.java
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/patch.sh
  samples/extension-template/README.md
  samples/extension-template/src/main/java/org/alfresco/sdk/sample/handler/HtmlContentCreatedHandler.java
Labels: PR: reviewed-approved

#148 ISSUE-77 Fix ACS auth API client
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/patch.sh
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-spring-boot/src/main/java/org/alfresco/rest/sdk/config/AlfrescoRestApiAutoConfiguration.java
Labels: PR: unreviewed

#151 ISSUE-109 Add support for multipart node creation
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/patch.sh
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/src/main/resources/sources/alfresco-core-rest-api/src/main/java/org/alfresco/core/handler/ContentApi.java
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/src/main/resources/sources/alfresco-core-rest-api/src/main/java/org/alfresco/core/handler/ContentApiClient.java
  samples/extension-template/src/main/java/org/alfresco/sdk/sample/handler/HtmlContentCreatedHandler.java
  samples/extension-template/src/main/java/org/alfresco/sdk/sample/handler/HtmlFolderCreatedHandler.java
Labels: PR: reviewed-approved

#152 REPO-5614 New approach for code generation
  .gitignore
  .travis.yml
  README.md
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/README.md
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generate.sh
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-auth-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-core-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-discovery-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-governance-classification-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-governance-core-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-model-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-search-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-search-sql-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/README.md
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generate.sh
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-audit-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-deployment-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-dmn-simulation-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-form-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-modeling-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-preference-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-query-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-runtime-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-script-modeling-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/pom.xml
Labels: PR: unreviewed

#154 [AAE-8577] fix generating patch after swagger name polishing
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/patch.sh
  samples/java-rest-api-clients/src/main/java/org/alfresco/java/rest/client/sample/service/RESTClientService.java
Labels: PR: unreviewed, PR: draft, PR: partially-approved

#153 ISSUE-119 Setup artifact version for samples project
  samples/pom.xml
Labels: PR: partially-approved

#52 Tests added
  README.md
  integration-tests/pom.xml
  integration-tests/src/main/java/org/alfresco/core/TestApplication.java
  integration-tests/src/main/resources/application.properties
  integration-tests/src/test/java/org/alfresco/AbstractContentBasedIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/AbstractFolderBasedIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/AbstractNodeBasedIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/AbstractSiteBasedIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/CommentsApiServiceIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/DownloadsApiServiceIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/GroupsApiServiceIntegrationTests.java
  integration-tests/src/test/java/org/alfresco/core/NetworksApiServiceIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/NodesApiServiceIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/PreferencesApiServiceIntegrationTests.java
  integration-tests/src/test/java/org/alfresco/core/QueriesApiServiceIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/RenditionsApiServiceIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/SharedLinksApiServiceIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/SitesApiServiceIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/TagsApiServiceIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/TrashcanApiServiceIntegrationTest.java
  integration-tests/src/test/java/org/alfresco/core/VersionsApiServiceIntegrationTest.java
  integration-tests/src/test/java/util/Constants.java
  integration-tests/src/test/java/util/TestUtils.java
  pom.xml
Labels: PR: reviewed-approved
