Repository Alfresco/alfresco-java-sdk, pull requests merged in 2022-01, with the labels that each got.

#123 AAE-6597 Remove process storage from client generation
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/pom.xml
Labels: PR: unreviewed

#125 AAE-6349 use workspace to avoid to regenerate clients for deploy
  .travis.yml
Labels: PR: reviewed-approved

#132 AAE-6349 Remove double build in generation scripts
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generate.sh
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generate.sh
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-spring-boot/pom.xml
Labels: PR: reviewed-approved

#131 Release v5.1.3
  README.md
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/alfresco-event-gateway-api-client/README.md
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/alfresco-event-gateway-api-client/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-spring-boot-starter/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-spring-boot/pom.xml
  alfresco-acs-java-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-spring-boot-starter/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-spring-boot/pom.xml
  alfresco-apa-java-rest-api/pom.xml
  alfresco-java-event-api/alfresco-java-event-api-handling/pom.xml
  alfresco-java-event-api/alfresco-java-event-api-integration/pom.xml
  alfresco-java-event-api/alfresco-java-event-api-model/pom.xml
  alfresco-java-event-api/alfresco-java-event-api-spring-boot-starter/pom.xml
  alfresco-java-event-api/alfresco-java-event-api-spring-boot/pom.xml
  alfresco-java-event-api/pom.xml
  alfresco-java-rest-api-common/pom.xml
  pom.xml
  samples/event-api-handlers/pom.xml
  samples/event-api-spring-integration/pom.xml
  samples/extension-template/pom.xml
  samples/java-rest-api-clients/pom.xml
  samples/pom.xml
Labels: PR: partially-approved
