Repository Alfresco/alfresco-java-sdk, pull requests merged in 2023-03, with the labels that each got.

#184 Release v5.2.2
  README.md
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/alfresco-event-gateway-api-client/README.md
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/alfresco-event-gateway-api-client/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-auth-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-core-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-discovery-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-governance-classification-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-governance-core-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-model-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-search-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/generated/alfresco-search-sql-rest-api/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-lib/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-spring-boot-starter/pom.xml
  alfresco-acs-java-rest-api/alfresco-acs-java-rest-api-spring-boot/pom.xml
  alfresco-acs-java-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-audit-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-deployment-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-dmn-simulation-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-form-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-modeling-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-preference-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-query-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-runtime-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/generated/alfresco-activiti-script-modeling-rest-api/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-spring-boot-starter/pom.xml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-spring-boot/pom.xml
  alfresco-apa-java-rest-api/pom.xml
  alfresco-java-event-api/alfresco-java-event-api-handling/pom.xml
  alfresco-java-event-api/alfresco-java-event-api-integration/pom.xml
  alfresco-java-event-api/alfresco-java-event-api-model/pom.xml
  alfresco-java-event-api/alfresco-java-event-api-spring-boot-starter/pom.xml
  alfresco-java-event-api/alfresco-java-event-api-spring-boot/pom.xml
  alfresco-java-event-api/pom.xml
  alfresco-java-rest-api-common/pom.xml
  integration-tests/pom.xml
  pom.xml
  samples/event-api-handlers/pom.xml
  samples/event-api-spring-integration/pom.xml
  samples/extension-template/pom.xml
  samples/java-rest-api-clients/pom.xml
  samples/pom.xml
Labels: PR: reviewed-approved

#186 ACS-4766 Migrating to GH Actions 5.1.N
  .ci.settings.xml
  .github/workflows/ci.yml
  .travis.yml
  alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/README.md
  pom.xml
Labels: PR: unreviewed

#189 Add missing ciManagement section in pom.xml
  pom.xml
Labels: PR: partially-approved
